[structure]
components = "src/renderer/components"
utils = "src/renderer/utils"

[generator]
class_helper = "clsx"
import.components = "@renderer/components"
import.utils = "@renderer/utils"

[components.Button]

[components.Card]

[components.CopyUiProvider]
with-mdx-provider = false
with-toast-provider = false

[components.ScrollArea]

[components.Typography]
with-typography-codeblock = false

[components.Paper]

[utils.jss]

[utils.resolve-style2]
